[tool.poetry]
name = "redash-ai"
version = "0.1.0"
description = ""
authors = ["MoraaOntita"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^2.8.1"
langchain = "^1.0.8"
transformers = "^4.57.1"
langchain-community = {extras = ["sql"], version = "^0.4.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
